### ISSUE TITLE
Feature: Keepalive Option

### ISSUE THREAD

**Issue by X4** [arut/htstress#1]
Hi,

I'd like to tell you that your little tool is beating ab and weighttp when it comes to benchmarking raw performance without keepalive in all cases execpt with keepalive.
wrk is always faster, but only because it doesn't have an option for concurrent requests. Could you please implement a 'k' option that enabled HTTP keep-alive?
These are other http benchmarking tools I know and my humble opinion about them.
- siege - slow and single threaded
- ab - slow and single threaded
- httperf - difficult configuration, slow and single threaded
- weighttp - multithreaded, but slower than htstress without keepalive
- pounce - evented, but results fluctuate, it's sometimes faster than htstress 
- wrk - multithreaded, but doesn't offer concurrent connections and a keepalive switch

sources:
- https://github.com/lighttpd/weighttp
- https://github.com/X4/pounce
- https://github.com/wg/wrk

More tools:
http://www.opensourcetesting.org/performance.php
http://code.google.com/p/apib/
http://www.bauk.ws/baukbench/

**Comment by arut** [comment]
Thanks for response. I'll try to implement that a little later.

**Comment by X4** [comment]
@arut wow, that's great news! Thanks for taking these efforts!
I'll recommend  htstress
