### ISSUE TITLE
fatal error: 'sys/epoll.h' file not found

### ISSUE THREAD

**Issue by denji** [arut/htstress#2]
In Darwin error epool

Universal
- `libevent` http://libevent.org/ supports /dev/poll, kqueue(2), event ports, POSIX select(2), Windows select(), poll(2), and epoll(4)
- http://software.schmorp.de/pkg/libev.html

![dat1 t0](https://f.cloud.github.com/assets/3759759/691730/458ba232-dbb8-11e2-9385-7c90c922ff04.png)

**Comment by arut** [comment]
htstress has always been an ultralight Linux-only tool not requiring any third-party libs. Using libevent would change a lot in it. Maybe I will make a separate cross-platform version later.
